version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: seoul-toilet-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://seoul-toilet-db.c54o0kgo4e5o.ap-northeast-2.rds.amazonaws.com:5432/seoul_toilet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "80:8080"
    restart: unless-stopped
